return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "docker-compose-language-service",
      "eslint-lsp",
      "flake8",
      "gofumpt",
      "goimports",
      "gopls",
      "hadolint",
      "helm-ls",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "php-cs-fixer",
      "phpactor",
      "phpcs",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "stylua",
      "typescript-language-server",
    },
  },
}
